# Site
name: "While(True){Curious}"
description: "Yet Another Technical Blog..."
meta_description: "Technical Blog, Big Data, Data Engineering, Big Data Engineering, Data Science, Machine Learning, Spark, Hadoop, AWS"
logo: 'assets/images/wtc-logo-40.png'
favicon: 'assets/images/wtc-logo-40.png'
baseurl: ''
google_analytics: 'UA-131341253-1'
disqus: 'whiletruecurious'
mailchimp-list: 'https://whiletruecurious.com/mailchimp.html'

# Authors
authors:
  dev:
    name: Mukul Dev
    display_name: Mukul Dev
    gravatar: 9409e676297210cf0194e6f48019a5bd
    email: devmukul44@gmail.com
    web: https://www.linkedin.com/in/devmukul44/
    twitter: https://medium.com/@_dev
    description: "Big Data Engineering | Data Science | Proficient in designing and implementing distributed applications and highly available web services at scale. | Hands-on experience of BigData technologies including Spark, Hadoop, Parquet and Avro file format, ElasticSearch, Hbase."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge